### ISSUE TITLE
Add dependency to example

### ISSUE THREAD

**Issue by mulderp** [fahad19/grunt-stitch-extra#1]
Hi,

just looking at this, and it looks interesting to move from Stitch to Grunt. However, I am not sure how to deal with dependencies, include them, concat them?

In my Stitch package, I define:

<pre>
var package = stitch.createPackage({
  paths: [__dirname + '/client'],
  dependencies: [
    __dirname + "/vendor/backbone.obscura/backbone.obscura.js"
  ]
});
</pre>

How would this translate to `stitch_extra`?

**Comment by fahad19** [comment]
Given it is a Grunt plugin now, I would expect you would:
- concat your dependencies (like jQuery, Backbone): in `dependencies.js` file
- stitch your CommonJS files in `stitched.js` file
- concat both dependencies.js and stitched.js file into new `app.js` file
